# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded asteroidMonitoring 1.0 [list source [file join $dir asteroid-monitoring.tcl]]
package ifneeded crossedWires 1.0 [list source [file join $dir crossed-wires.tcl]]
package ifneeded fuelCounter 1.0 [list source [file join $dir fuel-counter.tcl]]
package ifneeded intCode 1.0 [list source [file join $dir intcode.tcl]]
package ifneeded miscUtils 1.0 [list source [file join $dir misc-utils.tcl]]
package ifneeded orbitMap 1.0 [list source [file join $dir orbit-map.tcl]]
package ifneeded passwords 1.0 [list source [file join $dir passwords.tcl]]
package ifneeded spaceImageFormat 1.0 [list source [file join $dir space-image-format.tcl]]
package ifneeded thrusters 1.0 [list source [file join $dir thrusters.tcl]]
