# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded crossed_wires 1.0 [list source [file join $dir crossed-wires.tcl]]
package ifneeded fuel_counter_upper 1.0 [list source [file join $dir fuel-counter-upper.tcl]]
package ifneeded intcode 1.0 [list source [file join $dir intcode.tcl]]
package ifneeded orbit_map 1.0 [list source [file join $dir orbit-map.tcl]]
package ifneeded passwords 1.0 [list source [file join $dir passwords.tcl]]
package ifneeded space_image_format 1.0 [list source [file join $dir space-image-format.tcl]]
package ifneeded thrusters 1.0 [list source [file join $dir thrusters.tcl]]
